name: Integration tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - uses: actions/checkout@v2
      - name: Build BigBlueSwarm artifact
        run: make build
      - name: Download BigBlueSwarm scripts
        run: make scripts
      - name: Run integration test cluster
        run: make test.integration.cluster.start test.integration.bigblueswarm.run
      - name: Launch integration tests
        run: make test.integration.launch
      - name: Stop integration test cluster
        run: make test.integration.bigblueswarm.stop cluster.stop test.integration.cluster.remove
